sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t prashantbadityahub/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true prashantbadityahub/react-test npm test

after_success:
  - docker build -t prashantbadityahub/multi-client ./client
  - docker build -t prashantbadityahub/multi-nginx ./nginx
  - docker build -t prashantbadityahub/multi-server ./server
  - docker build -t prashantbadityahub/multi-worker ./worker
  # Log in to the docker CLI......
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub.....
  - docker push prashantbadityahub/multi-client
  - docker push prashantbadityahub/multi-nginx
  - docker push prashantbadityahub/multi-server
  - docker push prashantbadityahub/multi-worker
